Bandcamp Downloader checks for valid URL.

diff --git a/bin/bandcamp_downloader b/bin/bandcamp_downloader
--- a/bin/bandcamp_downloader
+++ b/bin/bandcamp_downloader
@@ -10,7 +10,7 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-# Get Bandcamp URL
+# Get Bandcamp URL from first arguement
 if [[ -n "${1:-}" ]]; then
   url="$1"
 else
@@ -18,7 +18,7 @@ else
   exit 1
 fi
 
-# Download directory
+# Get download directory from second arguement
 if [[ -n "${2:-}" ]]; then
   downldDir="$2"
 else
@@ -34,13 +34,16 @@ json="$tempDir"/json
 songTitleFile="$tempDir"/song_title
 songUrlFile="$tempDir"/song_url
 
-# Extract JSON from HTML album page
+# Temporarily disable exit on error to check for valid URL.
+set +e
 
-echo "Downloading album data..."
-
+# Extract JSON from HTML album page. If grep returns no matches, URL is invalid.
 curl -sL "$url" \
   | grep -Po "(?<=trackinfo&quot;:\[).*?(?=\])" \
-  > "$json"
+  > "$json" \
+  || { echo "Error: Invalid URL!" >&2 && exit 2; }
+
+set -e
 
 # Extract song titles from JSON and put into file
 grep -Po "(?<=title&quot;:&quot;).*?(?=&quot;)" \
